name: Practice-basic-webapi-application Workflow

on: push

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: echo "Hello, World"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploy
        path: |
          src

  deploy:
    name: Deploy Artifact to Github Runner
    runs-on: [self-hosted, linux, dynamic-runner-service]
    needs: workflow

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy

    - name: Move to Automation folder
      run: |
        mkdir -p /app/pipeline-tooling/EnvironmentTokenReplacer
        chmod +x EnvironmentTokenReplacer
        mv EnvironmentTokenReplacer /app/pipeline-tooling/EnvironmentTokenReplacer
