# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Practice-basic-webapi-application Workflow

on:
  repository_dispatch:
    types: 
      - webhook-test
    
  push:
    branches: 
      - main
      - feature/DCE-153-walking-skeleton 

jobs:
  webhook-test:
    name: Webhook Test
    runs-on: ubuntu-latest 
    #[self-hosted, linux, x64, dm-dq-dynamic-runner, dotnet, ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: dotnet build ./src/Practice-basic-webapi-application/Practice-basic-webapi-application.csproj
     
    - name: Echo
      run: echo ${{ github.event.client_payload.text }}