name: Practice-basic-webapi-application Workflow

on: push

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: echo "Hello, World"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: |
          workflows

    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: code-coverage-report
    #     path: output/test/code-coverage.html
      