name: Practice-basic-webapi-application Workflow

on: push

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: echo "Hello, World"

    - name: Publish
      run: dotnet publish src/WebApi.csproj -r linux-x64 --self-contained=true -c Release -o dist /p:PublishSingleFile=true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: |
          dist

  artifact:
    name: Deploy Artifact to Github Runner
    runs-on: [self-hosted, linux, dynamic-runner-service]
    needs: workflow


