name: Practice-basic-webapi-application Workflow

on: push

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: echo "Hello, World"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: |
          src/bin/Debug/net6.0
      