name: Practice-basic-webapi-application Workflow

on: push

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: echo "Hello, World"

    - name: Publish
      run: dotnet publish src/WebApi.csproj -r win-x64 --self-contained=true -c Release -o release/win-x64 /p:PublishSingleFile=true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: | 
          ./release

  # artifact:
  #   name: Deploy Artifact to Github Runner
  #   runs-on: [self-hosted, linux, dynamic-runner-service]
  #   needs: workflow

  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: deploy


